[package]
name = "ballista-nyctaxi"
description = "Ballista example for NYC Taxi data"
version = "0.1.1"
license = "Apache-2.0"
edition = "2018"

[dependencies]
arrow = "0.14.0"
ballista = { path = "../../" }
