apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
spec:
  template:
    spec:
      containers:
        - name: application
          image: andygrove/ballista-nyctaxi:0.1.1
      restartPolicy: Never
  backoffLimit: 1