apiVersion: v1
kind: Pod
metadata:
  name: parallel-aggregate-rs
  labels:
    app: parallel-aggregate-rs
spec:
  containers:
    - name: parallel-aggregate-rs
      image: ballistacompute/parallel-aggregate-rs
